/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendRouteImport } from './routes/trend'
import { Route as FactsRouteImport } from './routes/facts'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YearMonthRouteImport } from './routes/$year.$month'
import { Route as YearMonthDayRouteImport } from './routes/$year.$month.$day'

const TrendRoute = TrendRouteImport.update({
  id: '/trend',
  path: '/trend',
  getParentRoute: () => rootRouteImport,
})
const FactsRoute = FactsRouteImport.update({
  id: '/facts',
  path: '/facts',
  getParentRoute: () => rootRouteImport,
})
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
})
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})
const YearMonthRoute = YearMonthRouteImport.update({
  id: '/$year/$month',
  path: '/$year/$month',
  getParentRoute: () => rootRouteImport,
})
const YearMonthDayRoute = YearMonthDayRouteImport.update({
  id: '/$day',
  path: '/$day',
  getParentRoute: () => YearMonthRoute,
})

const YearMonthRouteChildren = {
  YearMonthDayRoute: YearMonthDayRoute,
}

const YearMonthRouteWithChildren = YearMonthRoute._addFileChildren(
  YearMonthRouteChildren,
)

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  FactsRoute: FactsRoute,
  TrendRoute: TrendRoute,
  YearMonthRoute: YearMonthRouteWithChildren,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
